# =============================================================================
# CONFIGURATION.YAML INCLUDE STRUCTURE FOR HEATING SCHEDULE
# Copy these lines to your main configuration.yaml file
# =============================================================================

# Include heating schedule input helpers
input_boolean: !include heating_schedule_helpers.yaml
input_datetime: !include heating_schedule_times.yaml
input_number: !include heating_schedule_temperatures.yaml

# Include heating schedule template sensors
template: !include heating_schedule_templates.yaml

# =============================================================================
# ALTERNATIVE: Merge with existing includes
# If you already have input_boolean, input_datetime, input_number, or template
# sections in your configuration.yaml, you'll need to merge them like this:
# =============================================================================

# OPTION 1: If you have existing input helpers, merge them
# input_boolean: !include_dir_merge_named input_helpers/
# input_datetime: !include_dir_merge_named input_helpers/
# input_number: !include_dir_merge_named input_helpers/

# OPTION 2: If you have a single file for each type, merge manually
# input_boolean:
#   existing_boolean_1:
#     name: "Existing Boolean"
#   # ... your existing booleans ...
#
#   # Add heating schedule booleans here:
#   heat_schedule_enabled:
#     name: "Heat Schedule Enabled"
#     icon: mdi:thermostat
#   # ... etc

# OPTION 3: Use include_dir_merge_list for templates if you have multiple template files
# template: !include_dir_merge_list templates/

# =============================================================================
# DIRECTORY STRUCTURE RECOMMENDATION:
#
# config/
# ├── configuration.yaml
# ├── heating_schedule_helpers.yaml
# ├── heating_schedule_times.yaml
# ├── heating_schedule_temperatures.yaml
# └── heating_schedule_templates.yaml
#
# OR organize in subdirectories:
#
# config/
# ├── configuration.yaml
# ├── heating_schedule/
# │   ├── helpers.yaml
# │   ├── times.yaml
# │   ├── temperatures.yaml
# │   └── templates.yaml
# └── other_includes/
# =============================================================================